### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by erikriver** [horazont/aioxmpp#1]
Hello, I tried to use the module but is not clear without documentation, although I readed the tests but is not enough understand to use with real cases with the protocol.

I will appreciate if you show some examples.

Thank you.

**Comment by horazont** [comment]
Hi,

Please note that this library is not suited for production and that I’m in the middle of a more-or-less large rewrite in the major-td-refactor branch, which is also not suited for production yet.

If you still want an example for the devel branch, I am happy break one out of my local test scripts.

regards,
horazont

**Comment by horazont** [comment]
@erikriver I worked on the new branch in the recent days and I also wrote a public example during that. You can check it out at devel in the examples subdirectory.

Writing a setup.py is on my TODO, but until that is done, you can do (from within the examples subdirectory):

    PYTHONPATH=.. python3 list_presence.py

to run the example.
