### ISSUE TITLE
XEP-0379 (Pre-Authenticated Roster Subscription) support

### ISSUE THREAD

**Issue by horazont** [horazont/aioxmpp#104]
[XEP-0379 (Pre-Authenticated Roster Subscription)](https://xmpp.org/extensions/xep-0379.html)

**Comment by sebastianriese** [comment]
Note: We decided to only provide XSO definitions for the element. Actually handling PARS will be the Client's task (that is: provide and manage tokens, handle token redeeming and sending automatic subscribed replies).
