### ISSUE TITLE
Port aioxmpp.avatar to aioxmpp.pep

### ISSUE THREAD

**Issue by sebastianriese** [horazont/aioxmpp#108]
Currently `aioxmpp.avatar` uses `aioxmpp.pubsub` directly. As it is a PEP node it should use `aioxmpp.pep`. Doing this closes #65 since empty notifies are ignored (since the are not allowed by PEP).

**Comment by horazont** [comment]
@sebastianriese How do you plan to resolve the issue that the PEP implementation does not really support "split" services such as the current implementation of Avatar?

**Comment by sebastianriese** [comment]
I would merge the services (especially, since this costs nothing, as we discussed: the server part costs nothing if we do not send an avatar, the client part costs nothing if we disable the `+notify` feature, which can be easily be done).
