### ISSUE TITLE
dnspython3 is replaced with dnspython

### ISSUE THREAD

**Issue by jomag** [horazont/aioxmpp#109]
While going through the dependencies of aioxmpp I found that "dnspython3" should be replaced with "dnspython". From pypi:

> dnspython3 has been superseded by the regular dnspython kit, which now supports both Python 2 and Python 3.
> 
> Installing this kit will simply cause the regular dnspython kit to be installed as a dependency.

**Comment by horazont** [comment]
Thanks for reporting, will be fixed in the next release (0.9), which, barring any surprises while merging #111, will be out in the next seven days.
