### ISSUE TITLE
No license file included in the tarball on pypi

### ISSUE THREAD

**Issue by jomag** [horazont/aioxmpp#112]
The license files (COPYING.LESSER etc) are not included in the tarball on pypi. When creating Yocto recipes there's a requirement to point to the license file and its checksum, so it would be very helpful if it was included. Same goes for aiosasl and aioopenssl by the way...

**Comment by horazont** [comment]
@jomag Thanks for reporting. I opened corresponding issues on aiosasl and aioopenssl, too. I won’t be able to make that change today or possibly even this weekend, but it’ll be done for v0.9 which should be released some time next week.

**Comment by horazont** [comment]
@jomag Can you please check if feature/install-license-file is sufficient for your purposes?

**Comment by jomag** [comment]
Yes! Thanks!

**Comment by horazont** [comment]
@jomag FYI, I uploaded 0.3.1 of both aioopenssl and aiosasl to PyPI just now. Those include the license files, hopefully.
