### ISSUE TITLE
Add method to disable XEP-0198

### ISSUE THREAD

**Issue by jomag** [horazont/aioxmpp#114]
In some cases it's preferable to disable stream management.

My current use case is that I have a device that use aioxmpp for communication. It's supposed to have a quite stable network connection. But when the network goes down, for any reason, I would prefer to be notified immediately of the problem. I'm not an expert at XEP-0198, but I think it's because of the stream management that the connection is displayed as alive for a long while after the network goes down.

I've been informed that there is currently no way to disable XEP 0198.

**Comment by horazont** [comment]
I marked this for 0.9 for now; I have made a quick triage of the issue and it appears to be easy to implement a switch for this, so it should be doable to put this in 0.9 without much hassle.

The use-case is one I had not thought of, but makes sense (e.g. unplugging an IoT device or something).

Please note that disabling XEP-0198 is no guarantee that the session will be closed quickly; there are lots of things at play here, including ARP cache and TCP timeouts (with the latter normally being exorbitantly large). You may need additional server-side measures to make sure that no dead connections linger around.

**Comment by horazont** [comment]
I just now learnt that it’s possible to set a maximum resumption time from the client. So I’d suggest that we implement a way to set that maximum resumption time, including to 0.

So we’ll implement a way to set that: this has the advantage that the other stream management features are still available, including possibly resumption if the time is set to a non-zero value and the network interruption is short.
