### ISSUE TITLE
[XEP-0048/bookmarks] Provide more convenient API

### ISSUE THREAD

**Issue by horazont** [horazont/aioxmpp#123]
I imagine the following interface:

```python
# emitted when a bookmark is added, either by remote or local party
on_bookmark_added = Signal()
# emitted when a bookmark is removed, either by remote or local party
on_bookmark_removed = Signal()
# emitted when a bookmark is changed, either by remote or local party
on_bookmark_changed = Signal()

async def add_bookmark(self, bookmark_xso):
    """
    Add or update a bookmark to server-side storage.
    """

async def update_bookmark(self, old, new):
    """
    Replace a bookmark.

    This operation fails if no bookmark equal to ``old`` is found. 
    Otherwise, ``old`` is replaced by ``new``. ``old`` must be equal 
    to ``new``.
    """

async def remove_bookmark(self, bookmark_xso):
    """
    Remove a bookmark from server-side storage.
    """

async def get_bookmarks(self):
    """
    Return all bookmarks from server-side storage.
    """

async def sync(self):
    """
    Force fetch of bookmarks from the server, unless PubSub is used. Emits events.
    """
```

Notes:
* the events shall not fire spuriously when multiple writes are required due to race conditions
* if pubsub storage is used, ``sync`` should be a no-op
* if private XML storage is used, ``sync`` must be called periodically to be able to emit the events
* add, remove and get also cause events to be emitted, since all will require reads of the remote storage
* equivalence of bookmarks depends on the type:

   * for ``<conference/>``: use bare jid for equality
   * for ``<url/>``: use url for equality

* equivalent bookmarks are not duplicated on ``add``, only updated
* equivalence is used to determine which bookmark to remove
* the user should not have to take care of performing multiple writes if a race condition with another entity occurs.
* a ``sync`` shall happen implicitly when the stream is established

**Comment by sebastianriese** [comment]
Question to the details of the proposal: How do we handle edits. If we do not want the front-end to have to repeat the bookkeeping we have to emit change events or timed remove/add events, which would have to be processed in sequential order to give correct results. This seems undesirable.

**Comment by horazont** [comment]
To sum up what we discussed earlier:

* Equality isn’t trivial. The intuitive approach is to declare conferences equal if the MUC JID is equal, however, in some cases it may make sense to have multiple bookmarks for the same room with different nicknames (I have those).

Now for the points you raised in chat earlier:

* I think it makes sense to implement this in the existing service (even though this breaks the interface).
* I think equality should be defined on the XSO classes (but not on the XSO module).
* A ``merge`` operation for XSOs *may* make sense. Not entirely trivial to define though since an absent attribute (in the Python sense, not in the XML sense) is currently entirely identical to an attribute which has its default value. This means that we cannot distinguish whether code assigned the default value to an attribute or whether no value has been assigned to an attribute at all. So the naive way of implementing a merge (to merge A and B, iterate over the attribute values of B and apply those which have been set to A) would not allow to set an attribute of A to a default value.

Further points:

* If it helps, we can abandon the well-defined handling of multiple conference bookmarks with different nicknames. I think however that a baseline of functionality should be there: it must be possible to targetedly remove such a duplicate bookmark. It is fine if we cannot create them.

* Making the change/replace operation a compare-and-exchange is reasonable and provides us with a well-defined way of handling things when we get into races with other clients.

* It may make sense to have different "update" methods for different bookmark types. That allows to easily handle those ambiguities without trickery. (Downside: it is harder for applications to define their own bookmark types.) For example:

   ```python
   async def set_conference_bookmark(self, jid, nick=None, *, 
                                     new_nick=None, new_description=None):
       pass
   ``` 

* If we don’t go that route, I’m a bit lost on how to implement updates cleanly with conference bookmarks. Changing the nickname of a bookmark is a thing which definitely needs to be well supported, and I’d like to see an ``on_bookmark_changed`` instead of a remove/add pair. Especially open for suggestions.

* Possibly we should take a look at advanced diff methods (difflib?) and clever tokenisation of the bookmarks, matching removed/added pairs to find those with equal room JID and emit ``on_bookmark_changed`` for those. This needs special handling for conferences.

* We could take a look how other clients implement this internally for API inspiration, even though I expect no handling for URL bookmarks for example.

* We could handle conferences special-cased internally and resort to some default ``==`` checks for other bookmark types (and define ``__eq__`` properly on the XSO classes).
