### ISSUE TITLE
XEP-0084: HTTP support

### ISSUE THREAD

**Issue by horazont** [horazont/aioxmpp#137]
Avatars can also be stored on some HTTP server. This is especially relevant given that XMPP servers will usually not allow clients to send large stanzas or store large blobs in PEP. This means that often, clients either do not upload ``image/png`` avatars at all (violating XEP-0084) or upload only a heavily downscaled avatar to PEP.

To implement this, an **optional** dependency on [aiohttp](https://github.com/aio-libs/aiohttp) should be added.

**up-for-grabs notes:** Please see the README and join our chat room if you want help or guidelines on how to implement this.

**Comment by sebastianriese** [comment]
A problem here is, that an application/desktop environment may want to configure the way HTTP are done (e.g. through a proxy), in this sense doing HTTP requests is difficult to do correctly from aioxmpp. At least there should be a hook to get a HTTP connection from the application. Further people may want to suppress HTTP avatar downloads for privacy reasons, etc.

Therefore I think this is out of scope for aioxmpp (although I am not opposed to adding a configuration hook, where an application can plug in the required HTTP support somehow).

**Comment by horazont** [comment]
I find that argument convincing.
