### ISSUE TITLE
Is it possible to insert a custom attribute to a <message/>?

### ISSUE THREAD

**Issue by javipalanca** [horazont/aioxmpp#149]
I'm trying to add custom attributes to a Message, but I'm not sure I've understood xso.
```
class Message(aioxmpp.Message):
    performative = aioxmpp.xso.Attr(tag="performative", 
                                    type_=aioxmpp.xso.String(),
                                    default="query")
```

This code is not resulting on receiving a message with a custom attribute.
I can't even print the message and see the new attribute. Could you please guide me to the solution?

**Comment by horazont** [comment]
I’m fairly certain you should not be doing that. May I ask what you’re trying to achieve? There may be an existing [XEP](https://xmpp.org/extensions/) which does what you want.

Usually, when extending stanzas, you’d add child elements. You can do that by patching the Message class:

```python
import aioxmpp.stanza
import aioxmpp.xso

aioxmpp.stanza.Message.performative = aioxmpp.xso.ChildText(
    ("your-namespace", "performative"),
    default="query",
)
```

Alternatively, if you **have** to use an attribute (e.g. if there’s a system you absolutely cannot change and with which you have to work), you can do so similarly:

```python
import aioxmpp.stanza
import aioxmpp.xso

aioxmpp.stanza.Message.performative = aioxmpp.xso.Attr(
    "performative",
    default="query",
)
```

Note that inheriting from ``aioxmpp.stanza.Message`` won’t work, because the XMLStream (or rather, the StanzaStream) only knows about ``aioxmpp.stanza.Message`` and will only try to deserialise that (or one of the other stanza classes).

**Comment by javipalanca** [comment]
Thanks a lot.
I'm adding custom semantic information which is not an existing XEP. You're right that I'd better inject a child element with this info and using my own namespace.
So, I cannot subclass the Message class, right? But I've tried to send a message with the ChildText of your example and the client didn't receive the new child element (as I could see in the debug console of the client)

**Comment by horazont** [comment]
In that case, can you please turn on debug logging and show logs from the message?

```python
# before importing aioxmpp
import logging
logging.basicConfig(level=logging.DEBUG)
```

This will create quite a bit of output. Please find the 'RECV' line where your message is received and show me the logs from that line onwards and also include the ``aioxmpp.xso.ChildText`` declaration you tried to use.

**Comment by javipalanca** [comment]
I've put the code in this gist https://gist.github.com/javipalanca/d17222430cee165892ef53af8a469c4a

In the example I send a message to myself, so I can paste you de SEND and RECV logs (which are unfortunately the same)
This is the output:

    DEBUG:aioxmpp.StanzaStream:forwarding stanza to xmlstream: <message from='jpalanca@localhost' to='jpalanca@localhost' id='x/9qolEcupaN+ZwvUapOq' type=<MessageType.CHAT: 'chat'>>

    DEBUG:aioxmpp.node.PresenceManagedClient.XMLStream:SENT b'<message from="jpalanca@localhost" to="jpalanca@localhost" id="x/9qolEcupaN+ZwvUapOq" type="chat"><body>Hello World!</body></message>'

    DEBUG:aioxmpp.node.PresenceManagedClient.XMLStream:RECV b"<message id='x/9qolEcupaN+ZwvUapOq' type='chat' from='jpalanca@localhost/00e76d69-b44a-40ca-bb1a-7e900afd8f81'><body>Hello World!</body></message>"

    DEBUG:aioxmpp.StanzaStream:incoming messgage: <message from='jpalanca@localhost/00e76d69-b44a-40ca-bb1a-7e900afd8f81' to=None id='x/9qolEcupaN+ZwvUapOq' type=<MessageType.CHAT: 'chat'>>

**Comment by horazont** [comment]
You’ve got a minor mistake there:
```python
aioxmpp.stanza.Message.fipa = Fipa()
```
This adds an instance of Fipa to the Message class – this is possible, but doesn’t do anything useful.

You should be doing instead (only once, e.g. at program startup or right after importing aioxmpp and defining your Fipa XSO):
```
aioxmpp.stanza.Message.fipa = aioxmpp.xso.Child([Fipa])
```
This lets Message know that it can have a child of class Fipa.

Now in your code to send the message, you’d do:
```python
msg = aioxmpp.Message(…)
msg.fipa = Fipa()  # only here you create a Fipa instance
msg.fipa.… = …
```

That should do the trick.

**Comment by javipalanca** [comment]
Thanks a lot! that worked! 👍

**Comment by horazont** [comment]
You’re welcome!
