### ISSUE TITLE
XEP-0045: Handle messages sent to the MUC during join

### ISSUE THREAD

**Issue by horazont** [horazont/aioxmpp#155]
Found by @ge0rg via jabbercat/jabbercat#21.

Messages sent with a MUC Room which has not completed the join yet are handled in a weird manner and we need to figure out how to do this right.

Protocol-wise, sending the message should be fine at that time. However, the occupant object for the local occupant isn’t set up properly yet, which leads to a problematic ``on_message`` event.

Possible solutions:

* delay the ``on_message`` event until the history replay has completed. This means that we need a queue for pending ``on_message`` events in MUC and we also need to time this carefully w.r.t. message tracking. Plus handling of join errors (the message should be bounced internally in that case).
* reject attempts to send a message before join has completed.

We only need an "okay" solution in aioxmpp. I think I could live with rejecting send attempts before the join has completed; clients should handle this properly anyways.

Thoughts?

**Comment by horazont** [comment]
Note: delaying until history replay is over is potentially bad because we might need to send a message to figure that out. Cf. https://prosody.im/issues/1053

**Comment by ge0rg** [comment]
What about triggering the on-message event when receiving the reflected message? You need to track outgoing messages for reflection anyway.

**Comment by horazont** [comment]
@ge0rg Normally, we trigger ``on_message`` right away when ``send_message_tracked`` is used, and the reflection is noted with a separate message-tracking related event.

So to defer ``on_message`` in this case would still need some kind of queue or list of pending ``on_message`` events in this case.

**Comment by horazont** [comment]
FWIW, we documented (3e0e1a5) the behaviour for now and will handle the quirks in jabbercat appropriately.
