### ISSUE TITLE
XEP-0092: Correctly handle requirement of name and version in result

### ISSUE THREAD

**Issue by horazont** [horazont/aioxmpp#168]
@sebastianriese correctly pointed out that XEP-0092 REQUIRES that ``<name/>`` and ``<version/>`` are included in a result.

We have three options:

* Force ``<name/>`` and ``<version/>`` to be the defaults (``"aioxmpp"``/``aioxmpp.__version__``) instead of None when deleted.
* Do not answer queries if either is set to None (reply with ``<service-unavailable/>``)
* Set them to ``"unspecified"``, ``"unspecified"`` instead.

Opinions?

**Comment by sebastianriese** [comment]
third option: raise when trying to "del" the property.
