### ISSUE TITLE
PEPClient: depend on EntityCapsService

### ISSUE THREAD

**Issue by horazont** [horazont/aioxmpp#179]
Given that PEP is rarely used without +notify and +notify doesn’t work without caps, why don’t we depend on it?

The answer and the fact that EntityCapsService must be loaded manually should be documented on the PEPClient class.

**Comment by horazont** [comment]
@sebastianriese ping.

**Comment by sebastianriese** [comment]
I would propose to simply add EntityCapsService to the dependencies (and document that for portability to old versions of aioxmpp you will have to load it manually).

**Comment by horazont** [comment]
Fixed in 35705f3.
