### ISSUE TITLE
Separate module for create_starttls_connection

### ISSUE THREAD

**Issue by delfick** [horazont/aioxmpp#19]
Hello,

I'm trying to use pyOpenSSL with asyncio and I came across https://github.com/horazont/aioxmpp/blob/devel/aioxmpp/ssl_transport.py

I was wondering if you could release it in it's own module please?

I've made a copy locally to see if it works and it does!

I want to use it without copying it straight into my project and without requiring all the other dependencies of aioxmpp.

Thanks!

Stephen.

**Comment by horazont** [comment]
Thanks for your interest in the module. Actually, refactoring that module into a separate package is appealing for several reasons, other people having interest in it just adds one more.

I’ll consider this for the near future, ideally this weekend when the 0.6 release of aioxmpp comes out :-). There are some things to consider though, and of course the administrative overhead of setting up repositories and such, so maybe I will not make it in time.

**Comment by delfick** [comment]
Fair enough, my project can wait for that :)

Thanks

**Comment by horazont** [comment]
@delfick see https://pypi.python.org/pypi/aioopenssl and https://github.com/horazont/aioopenssl

Please let me know if this works for you and if it does, close the issue.

**Comment by delfick** [comment]
Wow, so quick! Thank you so much.

That should be perfect.
