### ISSUE TITLE
Install fails because of setuptools version string

### ISSUE THREAD

**Issue by lovetox** [horazont/aioxmpp#192]
```python
if tuple(map(int, setuptools.__version__.split("."))) < (6, 0, 0):
    for i, item in enumerate(install_requires):
        install_requires[i] = item.replace("~=", ">=")
```
this fails because my setuptools version is

```python
>>> import setuptools
>>> setuptools.__version__
'39.0.1.post20180420'
```

i think you can remove the check, we are at setuptools version 39, the chances that someone uses 6 is low

**Comment by horazont** [comment]
Actually, 5.x is still on debian oldstable, which is why we have this thing in there. But sure, the check needs fixing.

**Comment by lovetox** [comment]
a easy fix seems to be only testing the major version, as everything < 6.0.0 will be not 6 in the first position
