### ISSUE TITLE
Loading xml2 lib does not work in MSYS2/Windows

### ISSUE THREAD

**Issue by lovetox** [horazont/aioxmpp#193]
if libxml2 is installed on Windows via MSYS2 the .dll is called `libxml2-2.dll`

So the code would have to be adapted

xml.py
```python
if os.name == 'nt':
    libxml2 = ctypes.cdll.LoadLibrary(
        ctypes.util.find_library("libxml2-2.dll"),
    )
```

i think over time you will have to test for multiple names, depending on where and how lxml is installed

**Comment by horazont** [comment]
Ideally, we should get rid of this dependency altogether. Can you provide a patch you tested to work in a PR please?
