### ISSUE TITLE
Problem installing aioxmpp library under Windows 10

### ISSUE THREAD

**Issue by jpwijbenga** [horazont/aioxmpp#234]
I'm trying to install this library under windows10. The pip install fails because libxml is not installed. However, when I install a newer version of libxml (4.2.4) from it is uninstalled because of the listerd requirement libxml ~= 3.6.0. Pip installer uninstalls my custom installed lxml 4.2.4 and tries to install version 3.8.0 (probably as the closest version it can find). I can't find a ready-madde version 3.8.0 for windows, so I guess the question is if the library works with 4.2.4 as well, and if so if the requirement can be upgraded. Cheers!

**Comment by horazont** [comment]
It will very likely work with 4.2.4. I actually use 4.2.4 on my dev machine.

**Comment by horazont** [comment]
The dependency was bumped to ``~4.0`` in 25d30532f86be5161820dae2aefc25960ccdef5e. This was even backported to 0.10.3.
