### ISSUE TITLE
AttributeError: 'Request' object has no attribute 'autoset_id'

### ISSUE THREAD

**Issue by akayunov** [horazont/aioxmpp#235]
Hello,
I run tests with aioxmpp by pytest and get next error:

============================================================================================== test session starts ==============================================================================================
platform linux -- Python 3.6.5, pytest-3.7.3, py-1.6.0, pluggy-0.7.1
rootdir: /opt/ca, inifile: pytest.ini
collected 1 item                                                                                                                                                                                                

tests/test_sendfile2.py F                                                                                                                                                                                 [100%]

=================================================================================================== FAILURES ====================================================================================================
_________________________________________________________________________________________________ test_sendfile _________________________________________________________________________________________________

create_user = <function create_user.<locals>.cu at 0x7f4c8dc3b048>

    def test_sendfile(create_user):
        create_user(USERS)
        recipient_jid = aioxmpp.JID.fromstr('{}@ips.unite.com'.format(USERS[0]['name']))
        sender_jid = aioxmpp.JID.fromstr('{}@ips.unite.com'.format(USERS[1]['name']))
    
        async def test_basic1():
            sender_client = aioxmpp.PresenceManagedClient(
                sender_jid,
                aioxmpp.make_security_layer('foobar1')
            )
    
            async with sender_client.connected() as stream:
    
                slot = await sender_client.send(aioxmpp.httpupload.Request(
                    'file1',
                    len(CONTENT),
                    'application/octet-stream',
                ))
    
        task = asyncio.ensure_future(test_basic1())
        loop = asyncio.get_event_loop()
>       loop.run_until_complete(task)

tests/test_sendfile2.py:42: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.6/asyncio/base_events.py:468: in run_until_complete
    return future.result()
tests/test_sendfile2.py:37: in test_basic1
    'application/octet-stream',
/usr/local/lib/python3.6/dist-packages/aioxmpp/node.py:1335: in send
    cb=cb))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <aioxmpp.stream.StanzaStream object at 0x7f4c8dc64ef0>, stanza = <aioxmpp.httpupload.xso.Request object at 0x7f4c8dc1e908>

    @asyncio.coroutine
    def _send_immediately(self, stanza, *, timeout=None, cb=None):
        """
            Send a stanza without waiting for the stream to be ready to send
            stanzas.
    
            This is only useful from within :class:`aioxmpp.node.Client` before
            the stream is fully established.
            """
>       stanza.autoset_id()
E       AttributeError: 'Request' object has no attribute 'autoset_id'

/usr/local/lib/python3.6/dist-packages/aioxmpp/stream.py:2490: AttributeError
=========================================================================================== 1 failed in 2.86 seconds ============================================================================================
root@88c9cfb4eba1:/opt/ca# 

[test_sendfile2.txt](https://github.com/horazont/aioxmpp/files/2328482/test_sendfile2.txt)

File with test in attach.

**Comment by horazont** [comment]
You have to wrap the request in an ``aioxmpp.IQ``. Please take a look at [the http upload example](https://github.com/horazont/aioxmpp/blob/devel/examples/upload.py#L212).

**Comment by akayunov** [comment]
You should mark it in documentations: https://docs.zombofant.net/aioxmpp/devel/api/public/httpupload.html
