### ISSUE TITLE
aioxmpp.httpupload.Request extention.

### ISSUE THREAD

**Issue by akayunov** [horazont/aioxmpp#236]
Hello,
I try to extend aioxmpp.httpupload.Request, but because some logic in metaclass get error like:

class XRequest(aioxmpp.xso.XSO): 
/usr/local/lib/python3.6/dist-packages/aioxmpp/stanza.py:1035: in as_payload_class
    cls.register_child(cls.payload, other_cls)
/usr/local/lib/python3.6/dist-packages/aioxmpp/xso/model.py:1999: in register_child
    raise ValueError("ambiguous Child")
E   ValueError: ambiguous Child

Why do you forbidden such extention? How can I extend request without monkey patching?
See test file in attach.
[test_sendfile_custom_request.txt](https://github.com/horazont/aioxmpp/files/2340520/test_sendfile_custom_request.txt)

**Comment by horazont** [comment]
If you registered two classes for the same thing, the parser cannot know which one to use when receiving a stanza. There must only ever be a single class for each TAG registered on an XML stream object.

To avoid this, you have two options:

* change the TAG in your subclass (only viable if you’re inventing a new protocol; rarely the right thing to do)
* monkey patch the existing class. This is the preferred and supported way for extending XSOs.

To avoid name collisions, you should prefix your monkey-patched attributes. E.g.:

```python
aioxmpp.httpupload.xso.Request.xep1234_foo = aioxmpp.xso.…
```

If your extension is proprietary, prefix it with your domain name or something.
