### ISSUE TITLE
Connecting to a server with self-signed certificate with aioxmpp

### ISSUE THREAD

**Issue by CarolineBoyer** [horazont/aioxmpp#238]
Hello,
I am currently trying to link a raspberry pi 3 sending information with a linux 18.04 hosting a prosody server. Using openSSL I created a certificate for my prosody server.

I decided to use aioxmpp on the Pi3 as a library to connect to my prosody server.
When using your piece of code in "Quick start" and built this piece of code :
```
import asyncio
import aioxmpp
import getpass


async def main():
        password = getpass.getpass()
        client = aioxmpp.PresenceManagedClient( 
                aioxmpp.JID.fromstr("username@serveripaddress"),
                aioxmpp.make_security_layer(password)
        )

        async with client.connected() as stream:
                print("connected")


loop = asyncio.get_event_loop()
loop.run_until_complete( asyncio.ensure_future(main()) )
loop.close()
```
username@serveripaddress is replaced by the account created in prosody.

Unfortunately, the stream is closed. I have no clue if it is a problem with prosody, my certificate (created using the prosodyctl) or the way I am using aioxmpp. So I am trying to start from the client point of view (aioxmpp)

In my terminal, when launching the script, it shows the following message :
```
certificate verification failed (by OpenSSL)
Fatal error on tls handshake
protocol: <aioxmpp.protocol.XMLStream object at 0x72f472b0>
transport: <aioopenssl.STARTTLSTransport object at 0x72f475d0>
[and so on]
```
I saw in your docs that you tested this with prosody, so I am guessing that you might have some clue on my issue.

Question : 
- How exactly should I use the library aioxmpp to tell it connect to a server using my certificate ?
Or do I just need to match the password with the passphrase used to created the certificate + key ?

This might sound very newbie, I apologize for this.

**Comment by horazont** [comment]
So, the issue is that you generated a self-signed certificate instead of using a "trusted" certificate, verified e.g. by LetsEncrypt or something. Sometimes, this is the only way (e.g. in a home setup). If you have the chance to use LetsEncrypt or a similar service, do so and the problem will vanish by itself.

If you cannot do that, you have to tell aioxmpp that the certificate is fine, even if it is not trusted by the Public Key Infrastructure (PKI) trust system (i.e. the big Certificate Authorities which are trusted by your operating system).

This is possible by using Certificate Pinning. With that, you can tell aioxmpp a list of certificates which it should consider okay for a domain, no matter what the PKI trust says. To do so, you have to pass additional arguments to ``make_security_layer``. First, you need to generate that information. It is a kind of fingerprint of the certificate you need. To generate that fingerprint, there is a [utility in the aioxmpp repository which you can simply download](https://github.com/horazont/aioxmpp/blob/devel/utils/cert_to_pk_pin.py). Example use:

```bash
python3 /path/to/cert_to_pk_pin.py /path/to/prosody.crt
```

... where ``prosody.crt`` is the certificate (*not* the private key, you’ll never need the servers *private* key for client operations) you’re using for prosody. The output will be a long string of characters, such as ``MIICIjANBgkqhkiG9w0B…``.

Now you need to modify your ``make_security_layer`` call to include this information. **Instead of**:

```python
aioxmpp.make_security_layer(password)
```

You would write:

```python
aioxmpp.make_security_layer(
    password,
    pin_type=aioxmpp.security_layer.PinType.PUBLIC_KEY,
    pin_store={"serveripaddress": ["MIICIjANBgkqhkiG9w0B…"]}
)
```

This way, you’re telling aioxmpp: "Hey, when connecting to "serveripaddress", it’s fine if the certificate matches "MIICIjANBgkqhkiG9w0B…", even if it is expired/untrusted/…. I have verified that certificate by other means.".

A couple of notes:

* Using an IP address directly is not a good idea. You might be running into a [known problem](https://docs.zombofant.net/aioxmpp/devel/user-guide/pitfalls.html#i-am-trying-to-connect-to-a-bare-ip-and-i-get-a-dns-error). I recommend add an entry in ``/etc/hosts`` and use a proper hostname instead (both on your client and on the prosody server). Of course, even better would be to make a proper DNS setup. The [prosody people have good documentation on that topic](https://prosody.im/doc/dns). Remember to update the ``pin_store`` information in your ``make_security_layer`` call when you fix the domain name. I think prosody doesn’t support bare IP addresses well either.

* Never, ever, ever, does anyone except the server providing the service need the private key or the password of the private key of the certificate. It is called a "private" key for that reason. It’s the core magic of the public key infrastructure system: the server has a secret, and via certificates we can verify (a) that the server indeed has the secret and (b) that somebody else has verified that the entity having the secret is allowed to provide services under a certain name (simplified).

* See also the documentation of [make_security_layer](https://docs.zombofant.net/aioxmpp/devel/api/public/security_layer.html#aioxmpp.security_layer.make).

**Comment by CarolineBoyer** [comment]
Thank you for taking the time to respond to me.

I have followed your instruction kind of blindly, though understanding the changes you asked me to do.
Unfortunately, I am receiving the same kind of message, just differently written : 

```
Fatal error on post-handshake callback
protocol: <aioxmpp.protocol.XMLStream object at 0x7373b350>
transport: <aioopenssl.STARTTLSTransport object at 0x7373b670>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/aioopenssl/__init__.py", line 375, in _tls_post_handshake_done
    task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/pi/.local/lib/python3.5/site-packages/aioxmpp/security_layer.py", line 472, in post_handshake
    raise errors.TLSFailure("certificate verification failed")
aioxmpp.errors.TLSFailure: TLS failure: certificate verification failed
connection failed: TLS failure: certificate verification failed

```
I did modify the script accordingly : 

```
                aioxmpp.make_security_layer(
                        password,
                        pin_type=aioxmpp.security_layer.PinType.PUBLIC_KEY,
                        pin_store={"serveripaddress": ["MIIBkjANBg..."]}
                )
        )

```

**Comment by horazont** [comment]
Hmmm, okay, that shouldn’t be the case. There is some mistake somewhere in your setup, I’m not 100% sure where though. One option is that you used the wrong certificate, or that you have configured prosody to use a different certificate than you think you did.

One way to check (given that you have a rather recent ``openssl`` installed) is, using a terminal:

```bash
openssl s_client -starttls xmpp -xmpphost serverip -connect serverip:5222
```

This command will output the certificate which the XMPP server uses, something like this:

```
Server certificate
-----BEGIN CERTIFICATE-----
MIIGVzCCBT+gAwIBAgISBPMBJtH3AJdWTIOn/1AU0bdFMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
…
DC9jfjHSAAp1dm3ps+vZAjH92V8m+eZYFJ0/CoDsamXFOnaPjSmsY8JEyg==
-----END CERTIFICATE-----
```

Copy the part between **and including** ``-----BEGIN CERTIFICATE-----`` and ``-----END CERTIFICATE-----`` into a file, and run ``cert_to_pk_pin.py`` on it. It should produce the same output as the previous run. If it does not, prosody is not using the certificate you think it is, which points to a prosody configuration mistake (try restarting it for example).

If the output is the same … I’m not sure where else to look, honestly. The public key pinning code path is rather well tested (in fact, it is used for all CI tests), I’d be very surprised to find a bug there.

Please check the above and report back if it doesn’t help… I’ll have to think of something else then :)

**Comment by CarolineBoyer** [comment]
The ouput is the same (I checked with a diff just in case). I wish I could give you more clues... To help at least a little...

At least I have learn a new command to check certificate.

**Comment by horazont** [comment]
Please add the following to the top of your script:
```python
import logging
logging.basicConfig(level=logging.DEBUG)
```
and paste the full output here. This enables super-verbose debug logging, maybe there’s a clue somewhere in there.

How did you install aioxmpp? Which version of aioxmpp is this?

**Comment by CarolineBoyer** [comment]
I installed aioxmpp using pip3.
It is the version 0.10

Here are the log you asked : Hope it will help !

```
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:aioxmpp.security_layer:using PublicKeyPinStore
DEBUG:aioxmpp.callbacks:connecting <bound method SimpleMessageDispatcher._feed of <aioxmpp.dispatcher.SimpleMessageDispatcher object at 0x736c3f50>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.callbacks:connecting <bound method SimplePresenceDispatcher._feed of <aioxmpp.dispatcher.SimplePresenceDispatcher object at 0x736c3fd0>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.callbacks:connecting <bound method PresenceServer._before_stream_established of <aioxmpp.presence.service.PresenceServer object at 0x736d10d0>>
DEBUG:aioxmpp.callbacks:connecting <bound method PresenceManagedClient._update_presence of <aioxmpp.node.PresenceManagedClient object at 0x736c3b30>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.node.PresenceManagedClient.on_stream_established:connecting <bound method PresenceManagedClient._handle_stream_established of <aioxmpp.node.PresenceManagedClient object at 0x736c3b30>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.node.PresenceManagedClient.on_stream_established:connecting <Future pending> with mode <bound method AdHocSignal.AUTO_FUTURE of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.node.PresenceManagedClient.on_failure:connecting <Future pending> with mode <bound method AdHocSignal.AUTO_FUTURE of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.callbacks:connecting <bound method Client._stream_failure of <aioxmpp.node.PresenceManagedClient object at 0x736c3b30>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.callbacks:connecting <bound method Client._stream_destroyed of <aioxmpp.node.PresenceManagedClient object at 0x736c3b30>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.node.PresenceManagedClient:no SRV records found for 129.6.60.38, falling back
DEBUG:aioxmpp.node.PresenceManagedClient:domain 129.6.60.38: trying to connect to '129.6.60.38':5222 using <aioxmpp.connector.STARTTLSConnector object at 0x73664250>
DEBUG:aioxmpp.callbacks:connecting <bound method XMLStream._deadtime_hard_limit_triggered of <aioxmpp.protocol.XMLStream object at 0x73664390>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.callbacks:connecting <aioxmpp.callbacks.AdHocSignal object at 0x73664490> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.node.PresenceManagedClient.XMLStream:SENT b'<?xml version="1.0"?><stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="129.6.60.38">'
DEBUG:aioopenssl.trace.fd=6:_write_ready: nothing more to write, removing writer
DEBUG:aioxmpp.node.PresenceManagedClient.XMLStream:RECV b"<?xml version='1.0'?><stream:stream xmlns:stream='http://etherx.jabber.org/streams' xml:lang='en' from='129.6.60.38' id='64ad419c-e0c1-4c79-9958-ef4eff833ec3' version='1.0' xmlns='jabber:client'><stream:features><starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'><required/></starttls></stream:features>"
DEBUG:aioxmpp.node.PresenceManagedClient.XMLStream:SENT b'<starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>'
DEBUG:aioopenssl.trace.fd=6:_write_ready: nothing more to write, removing writer
DEBUG:aioxmpp.node.PresenceManagedClient.XMLStream:RECV b"<proceed xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>"
DEBUG:aioopenssl.trace.fd=6:_initiate_tls called
DEBUG:aioopenssl.trace.fd=6:_tls_do_handshake called
DEBUG:aioopenssl.trace.fd=6:registering reader for _tls_do_handshake
DEBUG:aioopenssl.trace.fd=6:_tls_do_handshake called
DEBUG:aioxmpp.security_layer:certificate for '129.6.60.38' does not appear in pin store
DEBUG:aioxmpp.security_layer:certificate quick-check returned None
DEBUG:aioopenssl.trace.fd=6:registering reader for _tls_do_handshake
DEBUG:aioopenssl.trace.fd=6:_tls_do_handshake called
DEBUG:aioopenssl.trace.fd=6:clearing readers/writers
DEBUG:aioopenssl.trace.fd=6:handshake complete
DEBUG:aioopenssl.trace.fd=6:post handshake scheduled via callback
DEBUG:aioopenssl.trace.fd=6:_tls_post_handshake called
ERROR:asyncio:Fatal error on post-handshake callback
protocol: <aioxmpp.protocol.XMLStream object at 0x73664390>
transport: <aioopenssl.STARTTLSTransport object at 0x736646b0>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/aioopenssl/__init__.py", line 375, in _tls_post_handshake_done
    task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/pi/.local/lib/python3.5/site-packages/aioxmpp/security_layer.py", line 472, in post_handshake
    raise errors.TLSFailure("certificate verification failed")
aioxmpp.errors.TLSFailure: TLS failure: certificate verification failed
DEBUG:aioopenssl.trace.fd=6:_force_close called
DEBUG:aioopenssl.trace.fd=6:clearing readers/writers
DEBUG:aioopenssl.trace.fd=6:_waiter future done (<Future finished exception=TLSFailure('TLS failure: certificate verification failed',)>)
WARNING:aioxmpp.node.PresenceManagedClient:connection failed: TLS failure: certificate verification failed
DEBUG:aioxmpp.node.PresenceManagedClient.XMLStream:SENT b''
ERROR:aioxmpp.node.PresenceManagedClient:main failed
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/aioxmpp/node.py", line 824, in _on_main_done
    task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/pi/.local/lib/python3.5/site-packages/aioxmpp/node.py", line 989, in _main
    yield from self._main_impl()
  File "/home/pi/.local/lib/python3.5/site-packages/aioxmpp/node.py", line 951, in _main_impl
    logger=self.logger)
  File "/home/pi/.local/lib/python3.5/site-packages/aioxmpp/node.py", line 412, in connect_xmlstream
    raise exc
  File "/home/pi/.local/lib/python3.5/site-packages/aioxmpp/node.py", line 254, in _try_options
    base_logger=logger,
  File "/home/pi/.local/lib/python3.5/site-packages/aioxmpp/connector.py", line 264, in connect
    post_handshake_callback=verifier.post_handshake,
  File "/home/pi/.local/lib/python3.5/site-packages/aioxmpp/protocol.py", line 863, in starttls
    post_handshake_callback)
  File "/home/pi/.local/lib/python3.5/site-packages/aioopenssl/__init__.py", line 683, in starttls
    yield from self._waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/home/pi/.local/lib/python3.5/site-packages/aioopenssl/__init__.py", line 375, in _tls_post_handshake_done
    task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/pi/.local/lib/python3.5/site-packages/aioxmpp/security_layer.py", line 472, in post_handshake
    raise errors.TLSFailure("certificate verification failed")
aioxmpp.errors.TLSFailure: TLS failure: certificate verification failed
```

**Comment by horazont** [comment]
Ok. 1. can you please paste the complete code now? 2. can you please edit ``/home/pi/.local/lib/python3.5/site-packages/aioxmpp/security_layer.py`` and change (somewhere around line 562):
  ```python
        key = self._x509_key(x509)
        try:
            pins = self._storage[hostname]
        except KeyError:
            return None

        if key in pins:
            return True

        return None
  ```
  to
  ```python
        key = self._x509_key(x509)
        try:
            pins = self._storage[hostname]
        except KeyError:
            logger.debug("hostname %r not found in pin store %r", hostname, self._storage)
            return None

        if key in pins:
            logger.debug("certificate pin %r not found in pins %r", key, pins)
            return True

        return None
  ```

And re-run the script and paste the output.

**Comment by CarolineBoyer** [comment]
OH ! I think I have it :D * happy me *

I am very sorry for not understanding the serveripaddress part. 
Thank a lot for your help !

**Comment by horazont** [comment]
This will surely be useful to future readers, so that’s fine :-). Happy coding!
