### ISSUE TITLE
echo bot example

### ISSUE THREAD

**Issue by horazont** [horazont/aioxmpp#24]
As requested in #15 by @azmeuk.

**Comment by horazont** [comment]
Please see ``examples/echo_bot.py`` and the [relevant part in the quickstart guide](https://docs.zombofant.net/aioxmpp/devel/user-guide/quickstart.html#react-to-messages-echo-bot) (this link might break in the future, simply check the quickstart guide and search for Echo Bot). The quickstart guide features a more self-contained example than the ``echo_bot.py``.

@azmeuk Close if this is sufficient.

**Comment by azmeuk** [comment]
@horazont It is exactly what I looked for. Thanks
