### ISSUE TITLE
[Question] Publish-Subscribe client creation

### ISSUE THREAD

**Issue by CarolineBoyer** [horazont/aioxmpp#240]
Hello (again),
You were so helpful I was hoping you could help me on creating a Publish-Subscribe client.
Following your documentation, I changed my code creating a client to the following : 

```
import asyncio
import aioxmpp
import getpass
import lxml

async def main():
        jid = aioxmpp.JID.fromstr("account@ipaddr")
        password = getpass.getpass()
        client = aioxmpp.PresenceManagedClient(
                jid,
                aioxmpp.make_security_layer(
                        password,
                        pin_type=aioxmpp.security_layer.PinType.PUBLIC_KEY,
                        pin_store={"ipaddr": ["MIIBkjANBgkq....."]}
                )
        )

        pubsubClient = aioxmpp.PubSubClient(client)

          async with pubsubClient.connected() as stream:
                #print("connected")

                #Creating Node 
                nodeId = aioxmpp.PubSubClient.create(jid, "testingXMPP")

                #Creating Message need to be XML
                #parser = aioxmpp.xso.XSOParser()
                message =  lxml.etree.fromString("<message>Test</message>")
                aioxmpp.PubSubClient.publish( jid, nodeId, message ) 

async def forever():
        while True:
                await main()

loop = asyncio.get_event_loop()
loop.run_until_complete( forever() )
```

As a result I get : 

```
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:aioxmpp.security_layer:using PublicKeyPinStore
DEBUG:aioxmpp.callbacks:connecting <bound method SimpleMessageDispatcher._feed of <aioxmpp.dispatcher.SimpleMessageDispatcher object at 0x736d0030>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.callbacks:connecting <bound method SimplePresenceDispatcher._feed of <aioxmpp.dispatcher.SimplePresenceDispatcher object at 0x736d00b0>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.callbacks:connecting <bound method PresenceServer._before_stream_established of <aioxmpp.presence.service.PresenceServer object at 0x736d0190>>
DEBUG:aioxmpp.callbacks:connecting <bound method PresenceManagedClient._update_presence of <aioxmpp.node.PresenceManagedClient object at 0x736c4bf0>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.node.PresenceManagedClient.on_stream_established:connecting <bound method PresenceManagedClient._handle_stream_established of <aioxmpp.node.PresenceManagedClient object at 0x736c4bf0>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
Traceback (most recent call last):
  File "Desktop/xmppSensor.py", line 38, in <module>
    loop.run_until_complete( forever() )
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "Desktop/xmppSensor.py", line 35, in forever
    await main()
  File "Desktop/xmppSensor.py", line 21, in main
    pubsubClient = aioxmpp.PubSubClient(client)
  File "/home/pi/.local/lib/python3.5/site-packages/aioxmpp/pubsub/service.py", line 218, in __init__
    self._disco = self.dependencies[aioxmpp.DiscoClient]
KeyError: <class 'aioxmpp.disco.service.DiscoClient'>
```
Looks like the aioxmpp.PubSubClient(client) fails ? 
What kind of client are expecting if not a PresenceManagedClient ?

I am also not sure I understood how to deal with XSO object (how to create them, how to transport them, how to parse them).

And when creating a subscriber I would need to do the same script except I would need to replace the 
`aioxmpp.PubSubClient.publish( jid, nodeId, message ) ` to 
`aioxmpp.PubSubClient.subscribe( jid, "testingXMPP ) `
And use the XSOParser ?
Do I have to create a class such as the Message class in the documentation, forcing the XML to always have the same schema ?

I am very confused, thank you in advance for your help.

**Comment by horazont** [comment]
Sorry for the delay, I missed your question initially.

You have to instantiate Services like this:

```
pubsubClient = client.summon(aioxmpp.PubSubClient)
```

The [``summon`` method](https://docs.zombofant.net/aioxmpp/devel/api/public/node.html#aioxmpp.Client.summon) takes care of initialising the dependencies of the service, and it also makes sure that only one service of each type exists per client.

You can’t put arbitrary XML in aioxmpp, generally. You have to define the schema, as you already guessed. Here’s an example where I wrote a pubsub publisher:

* https://github.com/horazont/hint/blob/devel/aioserver/hintmodules/warnings/cap.py#L193 – declaration of the XSO
* https://github.com/horazont/hint/blob/devel/aioserver/hintmodules/warnings/xso.py#L64 (last line in the file) – registration of the XSO as valid PubSub item payload
* https://github.com/horazont/hint/blob/devel/aioserver/hintmodules/warnings/dwd.py#L393 – publishing of an Alert object

(sorry, that project is kind of a playground and thus not documented as thoroughly as aioxmpp ☹)

If you’ve ever worked with things like SQLAlchemy, the way how XSOs work should be familiar.

You don’t have to invoke XSOParser though – aioxmpp handles that for you.

Feel free to ask back. Good luck!

**Comment by CarolineBoyer** [comment]
Hello,

Thank you for your help, and sorry for not giving news earlier.

I think I understood a little bit more, but once again find myself to have an issue on I believe registering the XSO as valid PubSub item.

```
import asyncio

import aioxmpp
import aioxmpp.xso as xso
from aioxmpp.utils import namespaces

import getpass
import time
#import logging
#logging.basicConfig(level=logging.DEBUG)

# Creating the Messaging class containing Sensor Information
class Message(xso.XSO):
        TAG = (namespaces.client, "message")
        identifier = xso.ChildText(
                (namespaces.client, "identifier")
        )

        timestamp = xso.ChildText(
                (namespaces.client, "timestamp"),
                type_=xso.Float(),
        )

        value = xso.ChildText(
                (namespaces.client, "value"),
                type_ = xso.Float(),
        )

        unit = xso.ChildText(
                (namespaces.client, "unit"),
        )


async def main():
       #Client creation see message from before
       ........

        pubsubClient = client.summon(aioxmpp.PubSubClient)
        async with client.connected() as stream:
                #print("connected")

                #Creating Node 
                nodeId = aioxmpp.PubSubClient.create(jid, "testingXMPP")

                #Creating Message need to be XML
                message = Message()
                message.identifier = "Id_1"
                message.timestamp = time.time()
                message.value = 14
                message.unit = "C"
                await aioxmpp.PubSubClient.publish( jid, nodeId, message )

async def forever():
        #validating XSO
        aioxmpp.pubsub.xso.as_payload_class(Message)

        while True:
                await main()

loop = asyncio.get_event_loop()
loop.run_until_complete( forever() )
```


Line `await aioxmpp.PubSubClient.publish( jid, nodeId, message )` triggers an error such as following 
```
  File "xmppSensor.py", line 61, in main
    await aioxmpp.PubSubClient.publish( jid, nodeId, message )
TypeError: publish() missing 1 required positional argument: 'payload
```

I am guessing the payload is not considered as one ? I fail to understand what I did wrong...

**Comment by horazont** [comment]
You need to invoke the PubSubClient *methods* on the *object*, not on the class. Substitute ``aioxmpp.PubSubClient.create`` with ``pubSubClient.create``, and likewise for ``publish``.

Also, your code lacks the registration of the payload. Add the following in front of your ``class Message``:

```python
@aioxmpp.pubsub.xso.as_payload_class
class Message(xso.XSO):
```

Also, you should be using a different ``TAG`` for your sensor data. You are using the same namespace and local name as is used for the message stanza itself as defined in  RFC6120. While it will not be an issue in this case, it is discouraged to abuse elements like that.

**Comment by CarolineBoyer** [comment]
Silly me ! 
Thank you for your help so far. 
According to documentation : `aioxmpp.PubSubClient.create` returns "The name of the created node." (str). However, I can't seem to be able to reuse it in my `publish` method that according to the docs requires an (str) representing the Name of the PubSub node to publish to.

Any reason to see why the `create` method doesn't return  a str ?

**Comment by horazont** [comment]
You need to await it. It’s a coroutine.

**Comment by CarolineBoyer** [comment]
Hello, I apologize for my late response. 
By learning a little bit more about all this async in python, I understood how to await the coroutine. 
However by doing so, I seem to raise an <service-available> exception. 


```
Traceback (most recent call last):
  File "xmppSensor.py", line 79, in <module>
    loop.run_until_complete( forever() )
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "xmppSensor.py", line 74, in forever
    await main()
  File "xmppSensor.py", line 54, in main
    nodeId = await pubsubClient.create(jid, "testingXMPP")
  File "/home/pi/.local/lib/python3.5/site-packages/aioxmpp/pubsub/service.py", line 729, in create
    response = yield from self.client.send(iq)
  File "/home/pi/.local/lib/python3.5/site-packages/aioxmpp/node.py", line 1335, in send
    cb=cb))
  File "/home/pi/.local/lib/python3.5/site-packages/aioxmpp/stream.py", line 2577, in _send_immediately
    reply = yield from fut
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
aioxmpp.errors.XMPPCancelError: {urn:ietf:params:xml:ns:xmpp-stanzas}service-unavailable
```


As a reminder here is the piece of code :
```python

pubsubClient = client.summon(aioxmpp.PubSubClient)
async with client.connected() as stream:
	#Creating Node : if already existing, won't be created but updatedself.
	# A node is similar to a topic in MQTT
	nodeId = await pubsubClient.create(jid, "testingXMPP")
	print("NODEID")
	print(nodeId)
	print("___________")

	# XMPP transports message written in XML. Creating a MessageXMPP object.
	message = MessageXMPP()
	message.identifier = "Id_1"
	message.timestamp = time.time()
	message.value = 14.0
	message.unit = "C"

	# Publishing on the node|topic the message containing the data required.
	await pubsubClient.publish( jid, nodeId, message )
```

Following this [issue](https://github.com/horazont/aioxmpp/issues/75) referring to the [RFC](https://tools.ietf.org/html/rfc6120#section-8.4), I seem to understand this means it would mean the IQ stanza created by "pubsubClient.create" is not well created ? Which doesn't make any sense to me... 
As usual I guess :(

**Comment by horazont** [comment]
The error generally means that the requested service is not provided. This can mean that the ``jid`` does not offer PubSub services. Which jid is that, and how do you know that it supports pubsub?

**Comment by CarolineBoyer** [comment]
The jid I am using is the account/user I created on the Prosody server and has the required by RFC form: username [at] domain. 
And I have to be honest, I just created it using prosody user management command. 

Maybe my config file in Prosody doesnt enable the pubsub... That would be stupid of me, but I would have never thought of it... I'll check that and get back to you ! 

I'll post the code as an exemple of a pubsub (subscribe) in the end when everything is finally working (hopefully - crossing fingers), feel free to use it as an exemple in any documentation if you required such an exemple one day.

**Comment by horazont** [comment]
By default, PubSub on the user’s account itself (also known as PEP) isn’t enabled in prosody. You need to load the ``pep`` module to enable it.

We also have specific support for PEP-type use-cases in aioxmpp, if you are interested in that kind of stuff. Although I see some merit in first exploring the PEP use cases using the native PubSub API and then moving on to the PEP-specific wrappers, especially if this is a learning exercise :)

**Comment by CarolineBoyer** [comment]
This is definitely a learning exercice, trying to build the simplest script to allow a PubSub using XMPP. But I'll be sure to check into that, once I feel confident enough.

**Comment by CarolineBoyer** [comment]
I did it ! Thank you so much !

Here is an exemple of a publishing script :
```python
import asyncio
import aioxmpp
import aioxmpp.xso as xso
from aioxmpp.utils import namespaces

import getpass
import time
#import logging
#logging.basicConfig(level=logging.DEBUG)

@aioxmpp.pubsub.xso.as_payload_class
class MessageXMPP(xso.XSO):
	TAG = (namespaces.client, "messagexmpp")

	identifier = xso.ChildText(
		(namespaces.client, "identifier"),
	)

	timestamp = xso.ChildText(
		(namespaces.client, "timestamp"),
		type_=xso.Float(),
	)

	value = xso.ChildText(
		(namespaces.client, "value"),
		type_ = xso.Float(),
	)

	unit = xso.ChildText(
		(namespaces.client, "unit"),
	)


async def main():
	print("INFO : Starting connexion  ____")
	jid = aioxmpp.JID.fromstr(<username@domain>)
	password = <password>
	client = aioxmpp.PresenceManagedClient(
		jid,
		aioxmpp.make_security_layer(
			password,
			pin_type=aioxmpp.security_layer.PinType.PUBLIC_KEY,
			pin_store={<domain>: ["MIIBkjANBgkqh<key>"]}
		)
	)

	# Creation of the publish subscribe connection pattern
	pubsubClient = client.summon(aioxmpp.PubSubClient)

	async with client.connected() as stream:
		# Creating Node : if already existing, won't be created but updated itself.
		# Important notice : Creating note isn't needed if the module Pep is enabled on Prosody Server.
		# A node is similar to a topic in MQTT
		print("INFO : Creating Node  ____ \n\n\n")
		if (await pubsubClient.get_nodes(jid, "testingXMPP") is None ) :
			await pubsubClient.create(jid, "testingXMPP")



		# XMPP transports message written in XML. Creating a MessageXMPP object.
		message = MessageXMPP()
		message.identifier = "Id_1"
		message.timestamp = time.time()
		message.value = 14.0
		message.unit = "C"

		# Publishing on the node|topic the message containing the data required.
		print("INFO : Publishing Message ____ \n\n\n")
		await pubsubClient.publish( jid, "testingXMPP", message )
		print("INFO : Message Sent  ____")

async def forever():
	#await main()
	while True:
		await main()

loop = asyncio.get_event_loop()
loop.run_until_complete( forever() )
```


and the subscribing script :
```python
import asyncio
import aioxmpp
import aioxmpp.xso as xso
from aioxmpp.utils import namespaces

import getpass
import time
#import logging
#logging.basicConfig(level=logging.DEBUG)

@aioxmpp.pubsub.xso.as_payload_class
class MessageXMPP(xso.XSO):
	TAG = (namespaces.client, "messagexmpp")

	identifier = xso.ChildText(
		(namespaces.client, "identifier"),
	)

	timestamp = xso.ChildText(
		(namespaces.client, "timestamp"),
		type_=xso.Float(),
	)

	value = xso.ChildText(
		(namespaces.client, "value"),
		type_ = xso.Float(),
	)

	unit = xso.ChildText(
		(namespaces.client, "unit"),
	)


async def main():
	print("INFO : Starting connexion  ____")
	jid = aioxmpp.JID.fromstr(<username@domain>)
	password = <password>
	client = aioxmpp.PresenceManagedClient(
		jid,
		aioxmpp.make_security_layer(
			password,
			pin_type=aioxmpp.security_layer.PinType.PUBLIC_KEY,
			pin_store={<domain>: ["MIIBkjANBgkqh<key>"]}
		)
	)

	# Creation of the publish subscribe connection pattern
	pubsubClient = client.summon(aioxmpp.PubSubClient)

	async with client.connected() as stream:
		print("INFO : Subscribing to message ____\n\n\n")

		# Subscribing on the node|topic the message containing the data required.
		result = await pubsubClient.subscribe( jid, "testingXMPP" )
		print(result)

async def forever():
	#await main()
	while True:
		await main()

loop = asyncio.get_event_loop()
loop.run_until_complete( forever() )
```

**Comment by horazont** [comment]
:tada: Congratulations!

**Comment by horazont** [comment]
One thing to note though: You should not use namespaces.client in your own stuff. Invent your own namespace (if you don’t have a domain name or something to base it on, you can just generate a UUID and use it like this: ``urn:uuid:9482b604-cb89-48ea-ab7b-86a53a204e33``)

**Comment by horazont** [comment]
(Closing this now since you seem to be happy with your solution. Feel free to comment and/or reopen if there’s anything unclear.)

**Comment by bdpythondocker** [comment]
Hello guys, can you help me to fix this problem?
unhandleable IQ request: from=JID(localpart=None, domain='communication.com', resource=None), type_=<IQType.GET: 'get'>, payload=<aioxmpp.version.xso.Query object at 0x000001F02B797940>
