### ISSUE TITLE
[QUESTION] Can we start the client with access token ?

### ISSUE THREAD

**Issue by Mrerl** [horazont/aioxmpp#245]
Hello,
Can we start the client with access token ?

Thanks :p

**Comment by sebastianriese** [comment]
Please specify with more detail what you mean by starting the client with an access token, and link the standard you refer to. There are a few XEPs or ProtoXEPs that talk about access tokens, but no active standard document, and as far as I know none of those is supported by aioxmpp. If you implement the protocol yourself, we probably welcome a PR (depending on the deployment status of the protocol).
