### ISSUE TITLE
how can i write a server side application with aioxmpp

### ISSUE THREAD

**Issue by imliuda** [horazont/aioxmpp#25]
i am new with this library, and there are not much documents about it. i want some guidance. thanks.

**Comment by horazont** [comment]
Please clarify what you mean by "server-side". aioxmpp currently has no support for writing [XMPP Components (XEP-0141)][1] or implementing an XMPP server. It also is no priority to implement. Is that what you mean by "server-side"?

   [1]: https://xmpp.org/extensions/xep-0114.html

**Comment by imliuda** [comment]
i mean, implementing an XMPP server, which can use the same database and cache with my web app. forgive my poor English.

**Comment by horazont** [comment]
aioxmpp is not meant for developing XMPP Servers.

A good idea may be to look into the [prosody](https://prosody.im/) XMPP server, which is written in Lua and is highly extensible. There are modules to get user data from existing databases, so you may find a possible solution here.

**Comment by imliuda** [comment]
thanks!
