### ISSUE TITLE
[question] How to connect ?

### ISSUE THREAD

**Issue by Mrerl** [horazont/aioxmpp#252]
Hi,
I've see stanza.io, a js xmpp aio client, have more options for connection, 
for exemple, i have this : https://github.com/SzymonLisowiec/node-epicgames-client/blob/master/src/Communicator/index.js ... Can I do the same with aioxmpp ? 

Thanks a lot
Mr e-RL

**Comment by Mrerl** [comment]
this.stream = new StanzaIO.createClient({

			wsURL: 'wss://xmpp-service-prod.ol.epicgames.com',
			transport: 'websocket',
			server: 'prod.ol.epicgames.com',

			credentials: {
				host: 'prod.ol.epicgames.com',
				username: this.client.account.id,
				password: this.client.account.auth.access_token
			}

		});

**Comment by horazont** [comment]
No, we do not currently support websockets nor BOSH. See for example #18.

**Comment by rahulchhabra07** [comment]
Can this be mentioned in the documentation itself? Could have saved a ton of time if it was mentioned up front.

**Comment by horazont** [comment]
@rahulchhabra07 

Thanks for bringing this up. In theory, it is right there on the frontpage, since we don’t list the WebSockets RFC, nor the BOSH standards.

Feel free to file a separate issue for the documentation clarification.
