### ISSUE TITLE
XEP-0335: JSON Containers

### ISSUE THREAD

**Issue by horazont** [horazont/aioxmpp#271]
Should be provided in the aioxmpp.misc namespace. Maybe also register it as pubsub payload by default?

**up-for-grabs note**: Please see the README and join our chat room if you want help or guidelines on how to implement this.

**Comment by horazont** [comment]
I was thinking the other night. How do we want this? We could have a:

```python
class JSONContainer(aioxmpp.xso.XSO):
    ...
```

in addition to a character data XSO type which encapsulates JSON data according to the XEP. The JSONContainer could be registered as a pubsub payload right away if desired.

**Comment by sebastianriese** [comment]
So that we can mix-in the json container and then access the decoded json as an attribute (similar to how `HashesParent` works)?

**Comment by horazont** [comment]
Ha, I should’ve been more explicit.

```python
class JSONContainer(aioxmpp.xso.XSO):
    data = aioxmpp.xso.Text(type_=aioxmpp.xso.JSON)
```
