### ISSUE TITLE
XEP-0308 (Last Message Correction) support

### ISSUE THREAD

**Issue by lun-4** [horazont/aioxmpp#278]
[XEP-0308 (Last Message Correction)](https://xmpp.org/extensions/xep-0308.html) would be a nice XEP to be supported.

Maybe an `aioxmpp.Message.edited` boolean for when an incoming message is an edit of an already existing one?

**Comment by horazont** [comment]
Thanks for making an issue for this. I had this on my mental todo anyways, because [I needed XEP-0308 in another project](https://github.com/horazont/councilbot/blob/master/councilbot/bot.py#L67).

**Comment by LukeMarlin** [comment]
Hi @horazont , I started looking into that, and yes indeed that's basically what you said. Would you mind me opening the PR for this since it's almost your code? I have a working version as far as the code is concerned, and I've got the class commented, would something more be needed?

**Comment by horazont** [comment]
@LukeMarlin Yes, please go ahead.

A test which asserts that the ``.edited`` property (or however you called it) is actually a xso.Child descriptor which holds the respective sub-XSO would be good, but we can figure that out in the PR.
