### ISSUE TITLE
Parsing custom message

### ISSUE THREAD

**Issue by S-N-A** [horazont/aioxmpp#288]
Hi!
I have the following message from server:
```
<message from='jid1' to='jid2' id='104101166447' type='normal'><body/><root id='1'><vars><z id='1' name='name'/></vars></root><x xmlns='jabber:x:expire' seconds='86400'/></message>
```
How can i parse it using xso.XSO?

Tried the following code, but it didn't work:
```python
class Z(xso.XSO):
    TAG = None, 'z'
    id=xso.Attr('id', type_=xso.String()
    name=xso.Attr('name', type_=xso.String()
    text = xso.Text(default=None)

class Vars(xso.XSO):
    TAG = None, 'vars'
    z = xso.Child([Z])

class Root(xso.XSO):
    TAG = None, 'root'
    id = xso.Attr('id', type_=xso.String())
    vars = xso.Child([Vars])


Message.new_child = xso.Child([Root])
```

Help, please!

**Comment by horazont** [comment]
The ``TAG`` is incorrect. The elements are in the ``jabber:client`` namespace, because they do not have a prefix and messages in client-to-server streams are in the ``jabber:client`` namespace. So you have to do e.g.:

```
    TAG = 'jabber:client', 'root'
```

etc.

**Comment by S-N-A** [comment]
Thanks! It works now.

**Comment by horazont** [comment]
Note that it might generally not be a good idea to hijack the ``jabber:client`` namespace. Unless you have to parse a format from a source which is not under your control, you should avoid it.

It might be worthwhile reporting a bug against the software which produces that XML.
