### ISSUE TITLE
Extend version.Query with my own ChildText

### ISSUE THREAD

**Issue by vit1251** [horazont/aioxmpp#289]
I want extend aioxmpp.version.xso.Query my own additional ChildText.
XMPP server provide custom parameter with more parameters.
I create VersionQuery and inherit from XSO and receive exception on `register_child` (TAG already used).
I inherited VersionQuery from aioxmpp.version.xso.Query and receive validation error.

Please suggest me way to extend version XSO model:
- How to disable loading standard Query?
- How better way to manage loading services?

**Comment by vit1251** [comment]
It workaround solutions. How about register default plugins manual by user or replace decorator to another design solution. For example self.send(iq=iq) when iq.payload create __copy__ or make some context and instance depend solution.

**Comment by horazont** [comment]
> It workaround solutions. How about register default plugins manual by user or replace decorator to another design solution. For example self.send(iq=iq) when iq.payload create copy or make some context and instance depend solution.

No, this is how it’s supposed to work. We put quite a bit of effort into making this work correctly.

**Comment by vit1251** [comment]
> No, this is how it’s supposed to work. We put quite a bit of effort into making this work correctly.

I think in common case it work well but in some cases (custom server with custom underground extenstion and protocol implementation) it increase complexity and it one of my main reason to migrate to slixmpp as you know.
