### ISSUE TITLE
Echo bot example using message carbons

### ISSUE THREAD

**Issue by jearc** [horazont/aioxmpp#318]
The current [echo bot example](https://github.com/horazont/aioxmpp/blob/devel/examples/echo_bot.py) does not use message carbons, and hence fails if the XMPP account is logged in elsewhere.

**Comment by horazont** [comment]
@jearc Thanks. Please look at the file added in #319. This should do the trick. Please comment in #319 if this solves your issue! :)

**Comment by jearc** [comment]
That solved my issue exactly. Thanks a lot for your work.
