### ISSUE TITLE
Support for OMEMO ?

### ISSUE THREAD

**Issue by nicobo** [horazont/aioxmpp#338]
Hello.

Does aioxmpp supports OMEMO out of the box ?
If yes how to enable/configure it ?

I can't find "OMEMO" explicitly stated in the docs (I can see PEP but is it enough?).

**Comment by horazont** [comment]
Hi @nicobo,

Thanks for the question. There is nothing in aioxmpp which will handle the cryptographic details of OMEMO, nor the wire format of the most recent OMEMO draft.

All the building blocks are there, but there’s nothing "batteries included" style.

**Comment by nicobo** [comment]
Alright, have you heard of any good Python implementation ?

https://github.com/omemo/python-omemo looks empty .

https://github.com/Syndace/python-omemo seems better but documentation is still incomplete.

**Comment by horazont** [comment]
The one by Syndace should be good to go. I know it’s used in poezio and possibly Gajim. You can drop by the [jdev@muc.xmpp.org](xmpp:jdev@muc.xmpp.org?join) room for questions about python-omemo by Syndace.

**Comment by nicobo** [comment]
@horazont Thanks a lot !
