### ISSUE TITLE
aioxmpp incompatible with dnspython 2.0.0

### ISSUE THREAD

**Issue by jprokos** [horazont/aioxmpp#348]
When installing `aioxmpp` it removes dnspython 2.0.0 and installs dnspython 1.16.0

```
  Attempting uninstall: dnspython
    Found existing installation: dnspython 2.0.0
    Uninstalling dnspython-2.0.0:
      Successfully uninstalled dnspython-2.0.0
Successfully installed dnspython-1.16.0
```

**Comment by horazont** [comment]
Hi @jprokos,

Thanks for the hint. Currently, no such patch exists. But if you can provide one, that’d be very welcome. I’ll be mostly unavailable for maintenance tasks for the next two or three weeks.

**Comment by jprokos** [comment]
When updating other python packages I am warned.
Are these genuine incompatibilities?

```
aioxmpp 0.11.0 requires dnspython~=1.0, but you'll have dnspython 2.0.0 which is incompatible.
aioxmpp 0.11.0 requires multidict<5,>=2.0, but you'll have multidict 5.1.0 which is incompatible.
aioxmpp 0.11.0 requires tzlocal~=1.2, but you'll have tzlocal 2.1 which is incompatible.
```

**Comment by horazont** [comment]
No, it’s not incompatible. It works just fine on my machine. I am updating the setup.py file as we speak! Expect 0.12 in the next few days, with Python 3.9 support and updated metadata.

**Comment by horazont** [comment]
@jprokos  I just pushed 0.12.0 to PyPI, have fun! Debian packages are on the way, too.
