### ISSUE TITLE
Test test_error_dispatch fails with python 3.6

### ISSUE THREAD

**Issue by rku** [horazont/aioxmpp#35]
After upgrading python to 3.6, the test `test_error_dispatch` fails with the following error message:

```
Traceback (most recent call last):
  File "[..]/aioxmpp/tests/test_callbacks.py", line 521, in test_error_dispatch
    self.assertTrue(tl.error(obj))
  File "[..]/aioxmpp/aioxmpp/callbacks.py", line 169, in error
    self.fut.set_exception(exc)
TypeError: invalid exception object
```

**Comment by horazont** [comment]
This is a bug in the testsuite and has no effect on aioxmpp itself. 

It is safe to ignore that failure for now, and I will issue a bugfix release 0.7.3 soon to fix it.

**Comment by horazont** [comment]
Can you please check whether the hotfix/fix-broken-test-on-python3.6 branch fixes the issue?

**Comment by rku** [comment]
Looks good. Thanks!
