### ISSUE TITLE
quickstart_echo_bot does not work

### ISSUE THREAD

**Issue by pickerarm** [horazont/aioxmpp#351]
Hello. I am new at aioxmpp. after i enter my jid and password. program does not do  anything.

**Comment by horazont** [comment]
To enable me to help you, please answer the following questions:

1. What exactly did you do, ideally with full terminal output copy/pasted and all non-terminal actions you did in relation to this test?
2. What happened?
3. What did you expect to happen instead?

Thank you.

**Comment by pickerarm** [comment]
i copied all code(quickstart_echo_bot.py) and run. .it asks my jid and pwd in order.i enter my jabber id, password and enter then program waits. nothing happens

**Comment by pickerarm** [comment]
i have two jabber accounts. i sent messages from one to other.i expected to see my received message

**Comment by horazont** [comment]
When I do that, it works for me, so something is wrong on your end. Until you provide all details, I cannot help you, sorry.
