### ISSUE TITLE
Unable to create a MUC room #question

### ISSUE THREAD

**Issue by stampycode** [horazont/aioxmpp#353]
Hi,

I've been going over the documentation and the code, but can't see how my script can create a new MUC room, can someone please point me in the right direction for doing this using the library?
I have been able to change all room properties, join a room, leave a room, send and receive messages, etc.
I'm guessing there's some alternative terminology that I haven't figured out yet.

Thanks!

**Comment by stampycode** [comment]
I just answered my own question.

A room is created if it doesn't exist when you try to join it.

Duh.

**Comment by horazont** [comment]
Yes, this is how XMPP works. Some servers will require you to configure a room after creating it in that way, and will not allow others to join the room until you have configured it.

See also: https://xmpp.org/extensions/xep-0045.html#createroom
