### ISSUE TITLE
XEP-0085 (Chat State Notifications) support

### ISSUE THREAD

**Issue by horazont** [horazont/aioxmpp#49]
[XEP-0085 (Chat State Notifications)](https://xmpp.org/extensions/xep-0085.html)

**Comment by horazont** [comment]
In the light of #72, this should be handled in some mix-in for AbstractConversation subclasses so that this can be re-used in multiple implementations.

**Comment by sebastianriese** [comment]
See the discussion on #129: We do not provide a mix-in, but delegate the work to the application.
