### ISSUE TITLE
XEP-0049 (Private XML Storage) support

### ISSUE THREAD

**Issue by horazont** [horazont/aioxmpp#50]
[XEP-0049 (Private XML Storage)](https://xmpp.org/extensions/xep-0049.html)

**Comment by sebastianriese** [comment]
This is a legacy protocol and it would be nice if we would not have to support it. Sadly we seem to need it. The server support for needed fpr #45 does not seem to be universal. Plus it would be nice to be able to access bookmarks stored in private XML storage by other clients. To proceed with implementing bookmark storage I will implement this soon.

**Comment by sebastianriese** [comment]
Implemented in branch feature/private-xml-and-bookmarks. The documentation is still sparse. The e2e tests don't work with our prosody conifguration (and are therefore skipped).

**Comment by horazont** [comment]
Today-I-Heard (TIH) that somebody is actually working on support for this in Prosody. Treat this as rumor though.
