### ISSUE TITLE
[XEP-0198] Implement integer wraparound for SM counters

### ISSUE THREAD

**Issue by horazont** [horazont/aioxmpp#62]
XEP-0198 actually mandates that the counters must wrap around at 2³²-1. We don’t implement that currently.

**Comment by sebastianriese** [comment]
How about subclassing int to behave like uint32_t and have all the SM counters parsed to that class.

**Comment by horazont** [comment]
On March 30, 2017 1:29:11 AM CEST, Sebastian Riese <notifications@github.com> wrote:
>How about subclassing int to behave like uint32_t and have all the SM
>counters parsed to that class.

Hmm... Give it a shot, and see how the resumption behaviour around 2^32-1 is. That will definitely need testing.
-- 
Sent from my mobile device. Please excuse my brevity.

**Comment by horazont** [comment]
Fixed by merge of #67.
