### ISSUE TITLE
[XEP-0084] PubSub issues

### ISSUE THREAD

**Issue by sebastianriese** [horazont/aioxmpp#65]
XEP-0060 specifies in section 6.5.6:
> A service MAY return event notifications without payloads (e.g., to conserve bandwidth). If so, the client MAY request a specific item (using the ItemID) in order to retrieve the payload. When an entity requests items by ItemID, implementations MUST allow multiple items to be specified in the request.

This behaviour is currently not handled properly by the avatar service, which relies on the full payload being available with the push notifications from the server. This first part of the issue is easy to resolve.

However, in restricted network environments it may be undesirable to actually get the metadata (if we already can display an avatar with the given id from cache). This is a complex policy decision, which requires tight interaction with the user of the AvatarClient service.

Open Questions: Does PEP allow this as well? What about a decorator handling this automatically? How would the API for the user of the service optimally look like?

**Comment by horazont** [comment]
[XEP-0163 (Personal Eventing Protocol), section 5](https://xmpp.org/extensions/xep-0163.html#defaults):
> • Default the 'deliver_notifications' configuration option to true (i.e., deliver payloads by default).

So, by default, PEP will deliver us the data. However, a client could change that behaviour for the avatar node to annoy us (it doesn’t really make any sense to turn this off for the metadata node).

In that case, I’d fire the event without fetching the Avatar metadata and let the user of the service decide whether to fetch it or not (as you said, the ID is already sufficient to detect if the avatar is in the cache or not).

**Comment by sebastianriese** [comment]
However, that means, we need to change the signature and documentation of the signal. It has to have an `id_` argument and the metadata argument may be empty.

**Comment by horazont** [comment]
Assigning this to @sebastianriese because you have the closest experience with PEP etc.

**Comment by horazont** [comment]
@sebastianriese Am I correct in my assumption that this can be closed since we decided to simply drop the signal in those cases?

**Comment by sebastianriese** [comment]
No, it cannot yet be closed, since the avatar service is not ported to `aioxmpp.pep` yet. If this is done, this bug can be closed.

**Comment by horazont** [comment]
Closed via #108.
