### ISSUE TITLE
Improve stream aliveness checks (or: Timeouts Are Hard)

### ISSUE THREAD

**Issue by horazont** [horazont/aioxmpp#96]
This is for the near to middle future.

We currently have two key timeouts in aioxmpp:

1. ``negotiation_timeout``, which is used at several places during the initial stream setup (STARTTLS, SASL, resource binding). It is re-set on each step and indicates how long the response is allowed to take. It defaults at 60s (probably reasonable).
2. The ping timeout of the StanzaStream. This defaults at 15s(! this definitely needs changing). Some mobile links (which are *not* out of scope for aioxmpp because it may be used on Notebooks etc. using WWAN) have latency "spikes" (sometimes for minutes or longer) much worse than that.

I call for ideas what we can do here to provide useful timeouts by default while still letting the application override them.

Random stuff to keep in mind:

* We don’t want to lose an SM resumption opportunity because we didn’t figure out that the connection was dead until the session expired server-side. Unfortunately, servers don’t tell us how long they let the session linger (they may very well decide this based on load, too).
* We can use stanza reception as indicator of an alive connection, saves us from sending pings ("Economy Mode"?).
* We don’t want to let users wait too long on an obviously dead connection which could be resumed instantly, e.g. on switch between any of WWAN, WLAN and wired networks (maybe offer applications a way to force a ping with configurable timeout: that would allow them to send a ping with low timeout when the network connectivity was briefly interrupted)

**First idea:** measure the round-trip-time on connection setup and on subsequent pings, put it in a moving average and use this times three or four as a timeout for pings. Allow applications to configure that factor. Do not send pings if *something* was received within the last N seconds (add a callback in XMLStream to also detect stream-level whitespace, which is sometimes used as keep-alive), but force a full ping round-trip after M>N seconds.

**Comment by horazont** [comment]
Another thing to consider: on a very idle stream, we might run into NAT (or similar middle-boxes) timeouts for TCP connections if we don’t ping regularly. This is apparently a very valid consideration e.g. for long-lived push-service TCP connections.

yaxim apparently uses a ping interval of 14 minutes.

**Comment by horazont** [comment]
Another point from @ge0rg: Connection Reset By Peer interruptions are a hint on broken/timeouted NAT middle-boxes. We could try to use that as an indicator to reduce the ping interval accordingly.

**Comment by ge0rg** [comment]
While on sane networks, you should be able to get along with:

* packet timeout between 1 and 5 minutes (for authentication, ping etc) 
* ping the server after 15 or 45 minutes without incoming packets (either 0198 ack request or 0199 ping)
* ping / 0198 resume on connectivity change

I think that adaptive packet timeouts are an interesting thing, but in the general case you'll get a response within 60s. Latency spikes are typically outliers where you can do a 0198 resume afterwards. 

Most NATs come with acceptable timeouts, typically 60m. If you are on a broken network, you could attempt to work around it with adaptive ping intervals, but this is really a tiny minority. 

If you send a ping after a connection change,  your stack should be smart enough to close the connection. Then you can resume immediately.

**Comment by horazont** [comment]
How many servers still support 198 resumption after 45 minutes…?

Regarding the connection change, I’m not convinced. What I see in other applications is that they definitely run into a connection timeout. I guess this is because no application binds on the source address plus default routes which lead to black holes.

**Comment by horazont** [comment]
Default timeouts in the order of 15 minutes are definitely not a good idea for aioxmpp. We’re not targeting mobile phones. While notebooks can be on such networks too, they will rarely stand unused on a mobile (non-wifi) link (which is expensive in terms of power to operate) for long enough time for this to matter.

* Auto-pinging should be happening 1 to 5 minutes after the last data has been received (soft deadtime limit). A slow stream which continuously delivers data will thus never be pinged.
* Round-trip timeout should be in the order of 1 minute by default. This timeout is also used to form the hard deadtime limit (soft deadtime limit + round-trip timeout); the hard deadtime limit defines when the XML stream gets destroyed (and reconnection attempted) after the last data received from the server.


Plus the application should be pinging whenever it detects something fishy going on with the network (e.g. out-of-band signal that the connectivity has changed). Applications need a way to force a SM-reconnect (so that they can employ their own (lower) ping timeouts in those cases).
